# -*- coding: utf-8 -*-
"""dog_bread.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hXHDAujtpD1CszgpCIinOsId_Mub0WWa

lesson3- Digit classifier
"""
from fastbook import *
import timm
from fastai.vision.all import *
import gradio as gr
import os

learn = load_learner('model.pkl')
learn.predict(im)

